[font]
size = 15.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
opacity = 0.7

[window.padding]
x = 0
y = 0

[colors.primary]
background = "#090909"

[colors.cursor]
text = "#282828"
cursor = "#d4be98"

[colors.normal]
black = "#282828"
red = "#ea6962"
green = "#a9b665"
yellow = "#d8a657"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#d4be98"
